version: "3.9"
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    networks:
      - backend
    volumes:
      - wp:/www/wordpress
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - wp:/www/wordpress
    depends_on:
      - mariadb
    
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/abdel-ke/data/DB
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/abdel-ke/data/WordPress
      o: bind

networks:
  backend:
    driver: bridge